# Generated by Django 4.1.2 on 2024-07-01 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapatos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='activo',
        ),
        migrations.AddField(
            model_name='usuario',
            name='password1',
            field=models.CharField(default=1, max_length=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='password2',
            field=models.CharField(default=1, max_length=45),
            preserve_default=False,
        ),
    ]
