# Generated by Django 4.1.2 on 2024-07-01 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapatos', '0002_remove_usuario_activo_usuario_password1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='activo',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
