# Generated by Django 4.1.2 on 2024-07-02 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zapatos', '0003_usuario_activo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='password1',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='password2',
        ),
    ]
