# Generated by Django 4.1.2 on 2024-07-18 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapatos', '0004_remove_usuario_password1_remove_usuario_password2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zapato',
            fields=[
                ('id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.CharField(max_length=45)),
                ('imagen', models.ImageField(upload_to=None, verbose_name='')),
                ('activo', models.IntegerField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
