# Generated by Django 4.1.2 on 2024-07-18 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapatos', '0005_zapato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zapato',
            name='imagen',
            field=models.ImageField(null=True, upload_to='zapatos_nuevos'),
        ),
    ]
